# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/zte/blade_g/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/zte/blade_g/proprietary/lib/libaudcal.so:obj/lib/libaudcal.so \
    vendor/zte/blade_g/proprietary/lib/libaudioalsa.so:obj/lib/libaudioalsa.so

PRODUCT_COPY_FILES += \
    vendor/zte/blade_g/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
    vendor/zte/blade_g/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
    vendor/zte/blade_g/proprietary/lib/libaudioeq.so:system/lib/libaudioeq.so \
    vendor/zte/blade_g/proprietary/etc/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/zte/blade_g/proprietary/etc/firmware/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \
    vendor/zte/blade_g/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/zte/blade_g/proprietary/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
    vendor/zte/blade_g/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/zte/blade_g/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/zte/blade_g/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/zte/blade_g/proprietary/lib/egl/libGLESv2S3D_adreno200.so:system/lib/egl/libGLESv2S3D_adreno200.so \
    vendor/zte/blade_g/proprietary/lib/libgsl.so:system/lib/libgsl.so \
    vendor/zte/blade_g/proprietary/lib/libOpenVG.so:system/lib/libOpenVG.so \
    vendor/zte/blade_g/proprietary/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
    vendor/zte/blade_g/proprietary/lib/libc2d2_z180.so:system/lib/libc2d2_z180.so \
    vendor/zte/blade_g/proprietary/lib/libC2D2.so:system/lib/libC2D2.so \
    vendor/zte/blade_g/proprietary/bin/hciattach:system/bin/hciattach \
    vendor/zte/blade_g/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/zte/blade_g/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/zte/blade_g/proprietary/lib/libchromatix_hi542_default_video.so:system/lib/libchromatix_hi542_default_video.so \
    vendor/zte/blade_g/proprietary/lib/libchromatix_hi542_preview.so:system/lib/libchromatix_hi542_preview.so \
    vendor/zte/blade_g/proprietary/lib/libchromatix_imx074_default_video.so:system/lib/libchromatix_imx074_default_video.so \
    vendor/zte/blade_g/proprietary/lib/libchromatix_imx074_preview.so:system/lib/libchromatix_imx074_preview.so \
    vendor/zte/blade_g/proprietary/lib/libchromatix_imx074_video_hd.so:system/lib/libchromatix_imx074_video_hd.so \
    vendor/zte/blade_g/proprietary/lib/libchromatix_imx074_zsl.so:system/lib/libchromatix_imx074_zsl.so \
    vendor/zte/blade_g/proprietary/lib/libchromatix_imx091_default_video.so:system/lib/libchromatix_imx091_default_video.so \
    vendor/zte/blade_g/proprietary/lib/libchromatix_imx091_preview.so:system/lib/libchromatix_imx091_preview.so \
    vendor/zte/blade_g/proprietary/lib/libchromatix_imx091_video_hd.so:system/lib/libchromatix_imx091_video_hd.so \
    vendor/zte/blade_g/proprietary/lib/libchromatix_mt9e013_default_video.so:system/lib/libchromatix_mt9e013_default_video.so \
    vendor/zte/blade_g/proprietary/lib/libchromatix_mt9e013_preview.so:system/lib/libchromatix_mt9e013_preview.so \
    vendor/zte/blade_g/proprietary/lib/libchromatix_mt9e013_video_hfr.so:system/lib/libchromatix_mt9e013_video_hfr.so \
    vendor/zte/blade_g/proprietary/lib/libchromatix_ov2720_default_video.so:system/lib/libchromatix_ov2720_default_video.so \
    vendor/zte/blade_g/proprietary/lib/libchromatix_ov2720_hfr.so:system/lib/libchromatix_ov2720_hfr.so \
    vendor/zte/blade_g/proprietary/lib/libchromatix_ov2720_preview.so:system/lib/libchromatix_ov2720_preview.so \
    vendor/zte/blade_g/proprietary/lib/libchromatix_ov2720_zsl.so:system/lib/libchromatix_ov2720_zsl.so \
    vendor/zte/blade_g/proprietary/lib/libchromatix_ov5647_default_video.so:system/lib/libchromatix_ov5647_default_video.so \
    vendor/zte/blade_g/proprietary/lib/libchromatix_ov5647_preview.so:system/lib/libchromatix_ov5647_preview.so \
    vendor/zte/blade_g/proprietary/lib/libchromatix_ov5647_video_hfr.so:system/lib/libchromatix_ov5647_video_hfr.so \
    vendor/zte/blade_g/proprietary/lib/libchromatix_ov8825_default_video.so:system/lib/libchromatix_ov8825_default_video.so \
    vendor/zte/blade_g/proprietary/lib/libchromatix_ov8825_preview.so:system/lib/libchromatix_ov8825_preview.so \
    vendor/zte/blade_g/proprietary/lib/libchromatix_ov9726_default_video.so:system/lib/libchromatix_ov9726_default_video.so \
    vendor/zte/blade_g/proprietary/lib/libchromatix_ov9726_preview.so:system/lib/libchromatix_ov9726_preview.so \
    vendor/zte/blade_g/proprietary/lib/libchromatix_s5k3l1yx_default_video.so:system/lib/libchromatix_s5k3l1yx_default_video.so \
    vendor/zte/blade_g/proprietary/lib/libchromatix_s5k3l1yx_hfr_120fps.so:system/lib/libchromatix_s5k3l1yx_hfr_120fps.so \
    vendor/zte/blade_g/proprietary/lib/libchromatix_s5k3l1yx_hfr_60fps.so:system/lib/libchromatix_s5k3l1yx_hfr_60fps.so \
    vendor/zte/blade_g/proprietary/lib/libchromatix_s5k3l1yx_hfr_90fps.so:system/lib/libchromatix_s5k3l1yx_hfr_90fps.so \
    vendor/zte/blade_g/proprietary/lib/libchromatix_s5k3l1yx_preview.so:system/lib/libchromatix_s5k3l1yx_preview.so \
    vendor/zte/blade_g/proprietary/lib/libchromatix_s5k3l1yx_video_hd.so:system/lib/libchromatix_s5k3l1yx_video_hd.so \
    vendor/zte/blade_g/proprietary/lib/libchromatix_s5k3l1yx_zsl.so:system/lib/libchromatix_s5k3l1yx_zsl.so \
    vendor/zte/blade_g/proprietary/lib/libchromatix_s5k4e1_default_video.so:system/lib/libchromatix_s5k4e1_default_video.so \
    vendor/zte/blade_g/proprietary/lib/libchromatix_s5k4e1_preview.so:system/lib/libchromatix_s5k4e1_preview.so \
    vendor/zte/blade_g/proprietary/lib/libgemini.so:system/lib/libgemini.so \
    vendor/zte/blade_g/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/zte/blade_g/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/zte/blade_g/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/zte/blade_g/proprietary/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
    vendor/zte/blade_g/proprietary/lib/libmm-omxcore.so:system/lib/libmm-omxcore.so \
    vendor/zte/blade_g/proprietary/lib/libOmxCore.so:system/lib/libOmxCore.so \
    vendor/zte/blade_g/proprietary/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
    vendor/zte/blade_g/proprietary/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
    vendor/zte/blade_g/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
    vendor/zte/blade_g/proprietary/lib/libmmcamera_hdr_lib.so:system/lib/libmmcamera_hdr_lib.so \
    vendor/zte/blade_g/proprietary/lib/libmmcamera_image_stab.so:system/lib/libmmcamera_image_stab.so \
    vendor/zte/blade_g/proprietary/lib/libmmcamera_interface2.so:system/lib/libmmcamera_interface2.so \
    vendor/zte/blade_g/proprietary/lib/libmmcamera_statsproc31.so:system/lib/libmmcamera_statsproc31.so \
    vendor/zte/blade_g/proprietary/lib/libmmcamera_wavelet_lib.so:system/lib/libmmcamera_wavelet_lib.so \
    vendor/zte/blade_g/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
    vendor/zte/blade_g/proprietary/lib/libhardware_legacy.so:system/lib/libhardware_legacy.so \
    vendor/zte/blade_g/proprietary/lib/hw/camera.msm7x27a.so:system/lib/hw/camera.msm7x27a.so \
    vendor/zte/blade_g/proprietary/lib/libDivxDrm.so:system/lib/libDivxDrm.so \
    vendor/zte/blade_g/proprietary/lib/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
    vendor/zte/blade_g/proprietary/lib/libOmxAacDec.so:system/lib/libOmxAacDec.so \
    vendor/zte/blade_g/proprietary/lib/libOmxAacEnc.so:system/lib/libOmxAacEnc.so \
    vendor/zte/blade_g/proprietary/lib/libOmxAc3HwDec.so:system/lib/libOmxAc3HwDec.so \
    vendor/zte/blade_g/proprietary/lib/libOmxAdpcmDec.so:system/lib/libOmxAdpcmDec.so \
    vendor/zte/blade_g/proprietary/lib/libOmxAmrDec.so:system/lib/libOmxAmrDec.so \
    vendor/zte/blade_g/proprietary/lib/libOmxAmrEnc.so:system/lib/libOmxAmrEnc.so \
    vendor/zte/blade_g/proprietary/lib/libOmxAmrRtpDec.so:system/lib/libOmxAmrRtpDec.so \
    vendor/zte/blade_g/proprietary/lib/libOmxAmrwbDec.so:system/lib/libOmxAmrwbDec.so \
    vendor/zte/blade_g/proprietary/lib/libOmxEvrcDec.so:system/lib/libOmxEvrcDec.so \
    vendor/zte/blade_g/proprietary/lib/libOmxEvrcEnc.so:system/lib/libOmxEvrcEnc.so \
    vendor/zte/blade_g/proprietary/lib/libOmxEvrcHwDec.so:system/lib/libOmxEvrcHwDec.so \
    vendor/zte/blade_g/proprietary/lib/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \
    vendor/zte/blade_g/proprietary/lib/libOmxIttiamVdec.so:system/lib/libOmxIttiamVdec.so \
    vendor/zte/blade_g/proprietary/lib/libOmxIttiamVenc.so:system/lib/libOmxIttiamVenc.so \
    vendor/zte/blade_g/proprietary/lib/libOmxMp3Dec.so:system/lib/libOmxMp3Dec.so \
    vendor/zte/blade_g/proprietary/lib/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \
    vendor/zte/blade_g/proprietary/lib/libOmxOn2Dec.so:system/lib/libOmxOn2Dec.so \
    vendor/zte/blade_g/proprietary/lib/libOmxQcelp13Dec.so:system/lib/libOmxQcelp13Dec.so \
    vendor/zte/blade_g/proprietary/lib/libOmxQcelp13Enc.so:system/lib/libOmxQcelp13Enc.so \
    vendor/zte/blade_g/proprietary/lib/libOmxQcelpHwDec.so:system/lib/libOmxQcelpHwDec.so \
    vendor/zte/blade_g/proprietary/lib/libOmxrv9Dec.so:system/lib/libOmxrv9Dec.so \
    vendor/zte/blade_g/proprietary/lib/libOmxVp8Dec.so:system/lib/libOmxVp8Dec.so \
    vendor/zte/blade_g/proprietary/lib/libOmxWmaDec.so:system/lib/libOmxWmaDec.so \
    vendor/zte/blade_g/proprietary/lib/libOmxWmvDec.so:system/lib/libOmxWmvDec.so \
    vendor/zte/blade_g/proprietary/lib/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
    vendor/zte/blade_g/proprietary/lib/libmm-abl.so:system/lib/libmm-abl.so \
    vendor/zte/blade_g/proprietary/lib/libmm-abl-oem.so:system/lib/libmm-abl-oem.so \
    vendor/zte/blade_g/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
    vendor/zte/blade_g/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
    vendor/zte/blade_g/proprietary/lib/libmmparser.so:system/lib/libmmparser.so \
    vendor/zte/blade_g/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/zte/blade_g/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/zte/blade_g/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/zte/blade_g/proprietary/lib/libauth.so:system/lib/libauth.so \
    vendor/zte/blade_g/proprietary/lib/libcm.so:system/lib/libcm.so \
    vendor/zte/blade_g/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/zte/blade_g/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/zte/blade_g/proprietary/lib/libdsm.so:system/lib/libdsm.so \
    vendor/zte/blade_g/proprietary/lib/libdsprofile.so:system/lib/libdsprofile.so \
    vendor/zte/blade_g/proprietary/lib/libdss.so:system/lib/libdss.so \
    vendor/zte/blade_g/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/zte/blade_g/proprietary/lib/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/zte/blade_g/proprietary/lib/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/zte/blade_g/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/zte/blade_g/proprietary/lib/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/zte/blade_g/proprietary/lib/libnv.so:system/lib/libnv.so \
    vendor/zte/blade_g/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/zte/blade_g/proprietary/lib/liboem_rapi.so:system/lib/liboem_rapi.so \
    vendor/zte/blade_g/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/zte/blade_g/proprietary/lib/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/zte/blade_g/proprietary/lib/libqcci_legacy.so:system/lib/libqcci_legacy.so \
    vendor/zte/blade_g/proprietary/lib/libqdi.so:system/lib/libqdi.so \
    vendor/zte/blade_g/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/zte/blade_g/proprietary/lib/libqmi_client_qmux.so:system/lib/libqmi_client_qmux.so \
    vendor/zte/blade_g/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/zte/blade_g/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/zte/blade_g/proprietary/lib/libqueue.so:system/lib/libqueue.so \
    vendor/zte/blade_g/proprietary/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/zte/blade_g/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/zte/blade_g/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/zte/blade_g/proprietary/lib/libwms.so:system/lib/libwms.so \
    vendor/zte/blade_g/proprietary/lib/libwmsts.so:system/lib/libwmsts.so \
    vendor/zte/blade_g/proprietary/bin/akmd8963:system/bin/akmd8963 \
    vendor/zte/blade_g/proprietary/lib/hw/sensors.msm7x27a.so:system/lib/hw/sensors.msm7x27a.so \
    vendor/zte/blade_g/proprietary/bin/wifi_open.sh:system/bin/wifi_open.sh \
    vendor/zte/blade_g/proprietary/bin/wifi_close.sh:system/bin/wifi_close.sh \
    vendor/zte/blade_g/proprietary/lib/modules/librasdioif.ko:system/lib/modules/librasdioif.ko \
    vendor/zte/blade_g/proprietary/lib/modules/ath6kl/ath6kl_sdio.ko:system/lib/modules/ath6kl/ath6kl_sdio.ko \
    vendor/zte/blade_g/proprietary/lib/modules/ath6kl/cfg80211.ko:system/lib/modules/ath6kl/cfg80211.ko
