# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/zte/blade_g/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/zte/blade_g/proprietary/bin/mm-jpeg-dec-test:system/bin/mm-jpeg-dec-test \
    vendor/zte/blade_g/proprietary/bin/mm-vdec-omx-test:system/bin/mm-vdec-omx-test \
    vendor/zte/blade_g/proprietary/bin/mm-jpeg-enc-test:system/bin/mm-jpeg-enc-test \
    vendor/zte/blade_g/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/zte/blade_g/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/zte/blade_g/proprietary/bin/mm-venc-omx-test:system/bin/mm-venc-omx-test \
    vendor/zte/blade_g/proprietary/bin/test_gemini:system/bin/test_gemini \
    vendor/zte/blade_g/proprietary/bin/mm-jpeg-enc-test-client:system/bin/mm-jpeg-enc-test-client \
    vendor/zte/blade_g/proprietary/bin/akmd8963:system/bin/akmd8963 \
    vendor/zte/blade_g/proprietary/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
    vendor/zte/blade_g/proprietary/bin/cnd:system/bin/cnd \
    vendor/zte/blade_g/proprietary/bin/gpu_dcvsd:system/bin/gpu_dcvsd \
    vendor/zte/blade_g/proprietary/bin/mm-pp-daemon:system/bin/mm-pp-daemon \
    vendor/zte/blade_g/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/zte/blade_g/proprietary/bin/port-bridge:system/bin/port-bridge \
    vendor/zte/blade_g/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/zte/blade_g/proprietary/bin/wpa_supplicant:system/bin/wpa_supplicant \
    vendor/zte/blade_g/proprietary/bin/wifi_open.sh:system/bin/wifi_open.sh \
    vendor/zte/blade_g/proprietary/bin/wifi_close.sh:system/bin/wifi_close.sh \
    vendor/zte/blade_g/proprietary/bin/wiperiface:system/bin/wiperiface \
    vendor/zte/blade_g/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/zte/blade_g/proprietary/lib/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \
    vendor/zte/blade_g/proprietary/lib/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
    vendor/zte/blade_g/proprietary/lib/libmmcamera_hdr_lib.so:system/lib/libmmcamera_hdr_lib.so \
    vendor/zte/blade_g/proprietary/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
    vendor/zte/blade_g/proprietary/lib/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
    vendor/zte/blade_g/proprietary/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
    vendor/zte/blade_g/proprietary/lib/libgemini.so:system/lib/libgemini.so \
    vendor/zte/blade_g/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/zte/blade_g/proprietary/lib/libchromatix_s5k4e1_default_video.so:system/lib/libchromatix_s5k4e1_default_video.so \
    vendor/zte/blade_g/proprietary/lib/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \
    vendor/zte/blade_g/proprietary/lib/libmmcamera_image_stab.so:system/lib/libmmcamera_image_stab.so \
    vendor/zte/blade_g/proprietary/lib/libOpenVG.so:system/lib/libOpenVG.so \
    vendor/zte/blade_g/proprietary/lib/libchromatix_s5k4e1_preview.so:system/lib/libchromatix_s5k4e1_preview.so \
    vendor/zte/blade_g/proprietary/lib/libgsl.so:system/lib/libgsl.so \
    vendor/zte/blade_g/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
    vendor/zte/blade_g/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
    vendor/zte/blade_g/proprietary/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
    vendor/zte/blade_g/proprietary/lib/libc2d2_z180.so:system/lib/libc2d2_z180.so \
    vendor/zte/blade_g/proprietary/lib/libC2D2.so:system/lib/libC2D2.so \
    vendor/zte/blade_g/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/zte/blade_g/proprietary/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
    vendor/zte/blade_g/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/zte/blade_g/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/zte/blade_g/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/zte/blade_g/proprietary/lib/egl/libGLESv2S3D_adreno200.so:system/lib/egl/libGLESv2S3D_adreno200.so \
    vendor/zte/blade_g/proprietary/lib/egl/egl.cfg:system/lib/egl/egl.cfg \
    vendor/zte/blade_g/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
    vendor/zte/blade_g/proprietary/lib/libmmparser.so:system/lib/libmmparser.so \
    vendor/zte/blade_g/proprietary/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
    vendor/zte/blade_g/proprietary/lib/libaudioeq.so:system/lib/libaudioeq.so \
    vendor/zte/blade_g/proprietary/lib/libmmcamera_statsproc31.so:system/lib/libmmcamera_statsproc31.so \
    vendor/zte/blade_g/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
    vendor/zte/blade_g/proprietary/lib/libmmcamera_wavelet_lib.so:system/lib/libmmcamera_wavelet_lib.so \
    vendor/zte/blade_g/proprietary/lib/libmmcamera_interface2.so:system/lib/libmmcamera_interface2.so \
    vendor/zte/blade_g/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/zte/blade_g/proprietary/lib/libDivxDrm.so:system/lib/libDivxDrm.so \
    vendor/zte/blade_g/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/zte/blade_g/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/zte/blade_g/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/zte/blade_g/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/zte/blade_g/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/zte/blade_g/proprietary/lib/libqcci_legacy.so:system/lib/libqcci_legacy.so \
    vendor/zte/blade_g/proprietary/lib/libqdi.so:system/lib/libqdi.so \
    vendor/zte/blade_g/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/zte/blade_g/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/zte/blade_g/proprietary/lib/libqmi_client_qmux.so:system/lib/libqmi_client_qmux.so \
    vendor/zte/blade_g/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/zte/blade_g/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/zte/blade_g/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/zte/blade_g/proprietary/lib/libhardware_legacy.so:system/lib/libhardware_legacy.so \
    vendor/zte/blade_g/proprietary/lib/modules/librasdioif.ko:system/lib/modules/librasdioif.ko \
    vendor/zte/blade_g/proprietary/lib/modules/ath6kl/ath6kl_sdio.ko:system/lib/modules/ath6kl/ath6kl_sdio.ko \
    vendor/zte/blade_g/proprietary/lib/modules/ath6kl/cfg80211.ko:system/lib/modules/ath6kl/cfg80211.ko
